### ISSUE TITLE
document the functions to calculate network measures

### ISSUE THREAD

**Issue by ghost** [RogelioMart/twitterNetworkVisualizer#10]
https://networkx.github.io/documentation/stable/reference/algorithms/clustering.html
Shows how to do clustering coefficient.

https://networkx.github.io/documentation/stable/reference/algorithms/reciprocity.html
Shows how to do reciprocity

**Comment by RogelioMart** [comment]
https://networkx.github.io/documentation/stable/reference/algorithms/clustering.html
Shows how to do clustering coefficient.

https://networkx.github.io/documentation/stable/reference/algorithms/reciprocity.html
Shows how to do reciprocity
