### ISSUE TITLE
get Twitter dev access

### ISSUE THREAD

**Issue by ghost** [RogelioMart/twitterNetworkVisualizer#5]
Rogelio and I applied for Twitter dev accounts so we can access the Twitter API. Close this once we both are confirmed to have access.

**Comment by nschwei1** [comment]
I thought I signed up for a Twitter dev account but I guess I didn't finish or something. I'm going to apply again now.

**Comment by ghost** [comment]
Rogelio managed to get access and I gave up on getting an account and we decided to share one set of credentials.
